[project]
name = "zettel"
version = "0.1.0-9001"
description = "A package for notetaking inspired by the zettelkasten method"
readme = "README.md"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
